### ISSUE TITLE
Gnome 43

### ISSUE THREAD

**Issue by RaphaelRochet** [RaphaelRochet/circular-battery-indicator#2]
I've had a look on Gnome 43's new quicksettings menu.

I may be able to make this work with it, but can't test until I can install Gnome 43 on a real machine with a battery.

**Comment by raihan2000** [comment]
If you have any problem then I can test on my laptop on Gnome 43

**Comment by RaphaelRochet** [comment]
If you already have Gnome 43 on a laptop you may help me by checking this :

Type Alt+F2 to open run dialog, then "lg" and enter to open Looking glass tool. (Hit ESC to close it later)
![image](https://user-images.githubusercontent.com/1675389/193910917-b72da3e8-f87a-48d0-ab66-eb358435303b.png)

In the looking glass eval box (bottom), type ```Main.panel.statusArea.quickSettings._indicators.get_children()``` then enter :
![image](https://user-images.githubusercontent.com/1675389/193911283-b1f81bc0-d86e-4222-bdc6-d0c8da99d543.png)

Then click on the result line starting with _[0x_ and lots of numbers : 
![image](https://user-images.githubusercontent.com/1675389/193911479-8c9e945d-e5c7-4403-a622-670c587ee1b1.png)

A popup will come with values (lots of _Gjs_status_something_. I'm interested in what you will see there !

If you can't, that's fine. I will work on it as soon as Gnome 43 drops in Archlinux !

**Comment by raihan2000** [comment]
![Screenshot from 2022-10-05 11-33-42](https://user-images.githubusercontent.com/46452545/193992172-121a294a-519b-45e5-ac30-235c18ee73ca.png)
Sorry for late reply I think you need this, I'm not familier with gjs debugger, I will learn soon
![Screenshot from 2022-10-05 11-47-14](https://user-images.githubusercontent.com/46452545/193995267-c165c62a-f09a-46de-9641-245976a3c591.png)
![Screenshot from 2022-10-05 11-50-53](https://user-images.githubusercontent.com/46452545/193995491-22f360d6-cda8-4e81-93ef-8f9d911ecdaf.png)
![Screenshot from 2022-10-05 11-52-10](https://user-images.githubusercontent.com/46452545/193995516-ae99fa17-84e1-452e-8aa3-0c2b079adc6d.png)

**Comment by RaphaelRochet** [comment]
Thanks. I was kind of hoping to see a power/battery item, but looks like there's not. I will dive more in the source js.

BTW it's not gjs debugger, it's "Looking glass" tool. Much more like dev tools in browsers.

**Comment by RaphaelRochet** [comment]
Good news, I found where to look.

I could get to display that on the VM 
![image](https://user-images.githubusercontent.com/1675389/194019183-8946a00f-f7e6-48ca-9f1b-1e17944ddcda.png)

Bad news, it's way more complicated than before to patch. Will need a major rewrite.

**Comment by raihan2000** [comment]
Yes no power/battery is there. you have [status/system.js](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/status/system.js) in there you will find powerToggle I think.Yes to get it work again you have to rewrite it for Gnome 43.

**Comment by RaphaelRochet** [comment]
I've got some progress. Able to replace the battery icon with my drawing in quicksetting. 

![image](https://user-images.githubusercontent.com/1675389/194056201-38599046-54bd-46be-bae0-305b492aa91d.png)

However the sync between the quicksetting toggle and indicator is currently by icon filename.
Looks like I will need to hack it too and draw twice ...

**Comment by raihan2000** [comment]
Looks like circular-battery-indicator will be on Gnome 43 soon 😊🎉🎉🎉🎉

**Comment by RaphaelRochet** [comment]
Gnome 43 landed in Arch today, and with it v2 of circular-battery-indicator is now done :)
